#ifndef __PRODUCER_CONSUMER_H__
#define __PRODUCER_CONSUMER_H__

#include <queue>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <semaphore>
#include <deque>
#include <limits>

/* FULLY GENERATED BY AI */

/*
Thread-safe Producer-Consumer Queue
Lock-Free Producer, Lock-Protected Consumer.
Uses atomic stack for pushing and local cache for popping.
*/

template <typename T>
struct PCQNode {
    T data;
    PCQNode* next;
};

template <typename T>
class ProducerConsumerQueue {
private:
    std::atomic<PCQNode<T>*> head_{nullptr};
    std::counting_semaphore<std::numeric_limits<int>::max()> sem_{0};
    std::atomic<bool> signaled_{false};
    std::atomic<bool> stopped_{false};

    // Consumer side
    std::mutex consumer_mtx_;
    std::deque<T> consumer_cache_;

public:
    ProducerConsumerQueue() = default;
    
    // 복사 방지 (동기화 객체는 복사 불가)
    ProducerConsumerQueue(const ProducerConsumerQueue&) = delete;
    ProducerConsumerQueue& operator=(const ProducerConsumerQueue&) = delete;

    ~ProducerConsumerQueue();

    // Producer: 데이터 추가
    void push(T item);

    // Consumer: 데이터 꺼내기 (Blocking)
    // 큐에 데이터가 들어올 때까지 대기합니다.
    // stop()이 호출되어 종료되거나 큐가 비어있으면 false를 반환합니다.
    bool wait_and_pop(T& out_item);
    bool wait_and_pop_all(std::deque<T>& out_item);

    // Consumer: 데이터 꺼내기 (Non-blocking)
    // 큐가 비어있으면 즉시 false를 반환합니다.
    bool try_pop(T& out_item);

    // Consumer: 모든 데이터 꺼내기 (Batch Processing)
    // 락을 한 번만 걸고 큐의 모든 내용을 가져옵니다. (Swap 방식)
    std::deque<T> pop_all();

    // 상태 확인
    bool empty() const;

    size_t size() const;

    // 대기 중인 모든 Consumer를 깨우고 종료 상태로 전환
    void stop();
};

#include "producer_consumer.tpp"
#endif